### ISSUE TITLE
Code block: Add line numbers

### ISSUE THREAD

**Issue by falldowngoboone** [falldowngoboone/falldowngoboone-com#116]
Part of #122.

Looks like there's an issue with the Eleventy syntax highlighting plugin. I can add numbers by wrapping every line in a highlight:

```js
// .eleventy.js
eleventyConfig.addPlugin(syntaxHighlighting, {
  alwaysWrapLineHighlights: true,
});
```

Then I can use the resulting spans to add numbers via CSS counters:

```scss
// _vendor-prism-fdgb.scss

pre {
  counter-reset: lineNumber;
}
code .highlight-line:before {
  -webkit-user-select: none;
  border-right: 1px solid #404040;
  color: #858585;
  content: counter(lineNumber);
  counter-increment: lineNumber;
  display: inline-block;
  font-variant-numeric: tabular-nums;
  margin-right: 1.2em;
  padding-right: 1.2em;
  text-align: right;
  width: 2.4em;
}
```

However, the issue is some `br`s are being wrapped in a new `span`, causing the line highlighting to get all fouled up. I've seen this issue so far in `scss` blocks with a break between selectors: 

```scss
input:invalid,
[aria-invalid=true] {
  border-color: hsl(351, 100%, 27%);
}
```

<img width="835" alt="Incorrect formatting of CSS multiple-line selector list" src="https://user-images.githubusercontent.com/3603771/112762449-5a39d180-8fc5-11eb-84da-b5de4bded773.png">

`html` blocks that break to multiple lines:

```html
<input id="password" type="password" name="password" 
        aria-describedby="password-error" />
```

<img width="830" alt="Incorrect formatting of multiple line input" src="https://user-images.githubusercontent.com/3603771/112762519-a8e76b80-8fc5-11eb-869c-a90fe587a39d.png">

`jsx` blocks with nested JavaScript in brackets:

```jsx
export default function List({ items = [] }) {
  return (
    <ul class="styled-list">
      {Boolean(items.length) &&
        items.map((item) => <li class="styled-item" {...item} />)}
    </ul>
  );
}
```

<img width="834" alt="Incorrect formatting of returned JSX block with nested JavaScript" src="https://user-images.githubusercontent.com/3603771/112762559-d59b8300-8fc5-11eb-91ba-6c896a9c206b.png">

I've noticed changing `jsx` to `js` fixes that issue. Not sure about the rest. I would love to have line numbers, but I'm not sure that's currently possible with the Eleventy plugin.
